#!/bin/sh

OD=$(pwd)

# actualizar fuente
echo  'clonando manual de flujos.org'
cd wiki/
git clone git@flujos.org:manual.git src
cd ${OD}

# construir wiki
echo compilando wiki
ikiwiki --setup wiki.setup -refresh ${@}

# clonar fuente a carpeta de usuario src/wiki 
#mkdir config/chroot_local-includes/etc/skel/src
#git clone wiki/src config/chroot_local-includes/etc/skel/src/wiki
