#!/bin/sh

OD=$(pwd)

# actualizar fuente
echo actualizando fuente de manual
cd /home/kev/.usr/src/flujos/manual; git pull; cd ${OD}

echo  'clonando manual de flujos.org'
cd wiki/
git clone /home/kev/.usr/src/flujos/manual src
cd ${OD}

# construir wiki
echo compilando wiki
ikiwiki --setup wiki.setup --refresh ${@}

# clonar fuente a carpeta de usuario src/wiki 
#mkdir config/chroot_local-includes/etc/skel/src
#git clone wiki/src config/chroot_local-includes/etc/skel/src/wiki
