#!/bin/sh

# guardamos ubicacion actual en un variable 
OD=$(pwd)

# uri al fuente del manual
MAN_FUENTE="git://github.com/mictlan/fv-manual.git"

# clonar manual localmente
echo  'clonando manual de flujos.org'
cd wiki/
git clone ${MAN_FUENTE} src
cd ${OD}

# construir wiki
echo compilando wiki
ikiwiki --setup wiki.setup --refresh ${@}
