#!/bin/sh 
set -x
DEST="/var/www/live/"
VER=1.1a
URLS="http://flujos.org/fv/download http://live.acervo.org"
CHKSUM=md5sum
DIRS="iso-hybrid net squashfs"
FNAME="flujos-vivos-$VER-squeeze-i386"
CHANGELOG="git log --raw --date=iso --pretty=short"
# ${FNAME##*.} get extension

# build extra download methods

for dir in ${DIRS}
do
    if [ -d $dir ]; then
        cd $dir
        case ${dir} in
          iso-hybrid)
              zsyncmake ${FNAME}.iso -u $(echo $URLS | awk '{ print $1}')/${dir}/${FNAME}.iso -u $(echo $URLS |awk '{ print $2}')/${dir}/${FNAME}.iso
              ${CHKSUM} ${FNAME}.iso > ${FNAME}.iso.${CHKSUM}
          ;;
          squashfs)
              zsyncmake ${FNAME}.squashfs -u $(echo $URLS | awk '{ print $1}')/${dir}/${FNAME}.squashfs -u $(echo $URLS |awk '{ print $2}')/${dir}/${FNAME}.squashfs
              ${CHKSUM} ${FNAME}.squashfs > ${FNAME}.squashfs.${CHKSUM}
           ;;
          net)
              zsyncmake ${FNAME}-net.tar.gz -u $(echo $URLS | awk '{ print $1}')/${dir}/${FNAME}-net.tar.gz -u $(echo $URLS |awk '{ print $2}')/${dir}/${FNAME}-net.tar.gz -b 2048
              ${CHKSUM} ${FNAME}-net.tar.gz > ${FNAME}-net.tar.gz.${CHKSUM}
           ;;
         esac
         cd ../
    fi
done


# copy files de public html
for dir in ${DIRS}
do
    if [ -d $dir ]; then
    cp ${dir}/* ${DEST}/${dir}/
    fi
done

