#!/bin/sh -e

# Static variables
DISTRIBUTIONS="squeeze"
FLAVOURS="-flujos"

# Dynamic variables
#ARCHITECTURE="$(dpkg --print-architecture)"
ARCHITECTURE="i386"
DATE=$(date +%Y%m%d)
VERSION=1.1a
NAME="flujos-vivos-${VERSION}-${DISTRIBUTIONS}-${ARCHITECTURE}"
ISOHYBRID_OPTS="-entry 4 -type 1c"

genBinary ()
{
      TYPE=$*  # iso, usb-hdd, net, tar, squashfs
      buildIMG () 
        {
           
            lb clean noauto --purge
            
            #if [ -e .stage ]
            #    lb clean --purge
            #then
            #fi

            rm -rf cache/packages*
            rm -rf cache/stages_rootfs 
            echo "Build ${FNAME}"
            lb config -b ${TYPE}
            # build the wiki
            ./build-wiki 2>&1 | tee build-wiki.log
            lb build noauto ${@} 2>&1 | tee ${FNAME}.log
            echo "copying to ${FNAME}"
            if [ ! -d ${DNAME} ]; then
                mkdir ${DNAME}
            fi

            mv binary*[.,-]${EXT} ${DNAME}/${FNAME}
            if [ ${TYPE} = "iso-hybrid" ]; then
                ND="squashfs"
                if [ ! -d ${ND} ]; then
                    mkdir ${ND}
                fi
                mv binary/*/filesystem.squashfs ${ND}/${NAME}.squashfs

            fi
            for BINARY in $( ls binary[.,-]* )
            do
                if [ ${BINARY#*[.,-]} != "tar.gz" ]; then
                    mv ${BINARY} ${DNAME}/${FNAME}.${BINARY#*[.,-]}
                else
                    mv ${BINARY} ${DNAME}/${FNAME}
                fi
            done
        }
      case "${TYPE}" in 
        iso-hybrid)
            EXT=iso
            FNAME="${NAME}.${EXT}"
            DNAME="iso-hybrid"
            buildIMG
        ;;
        usb-hdd)
            EXT=img
            FNAME="${NAME}.${EXT}"
            DNAME="usb-hdd"
            buildIMG
        ;;
        net)
            EXT=net.tar.gz
            FNAME="${NAME}-${EXT}"
            DNAME="net"
            buildIMG
        ;;
    esac
}
        genBinary iso-hybrid 
        genBinary net 

