#!/bin/sh
BOOTAPPEND="locales=es_MX.UTF-8 keyboard-layout=latam"
LH_SYSLINUX_MENU_LIVE_ENTRY="Incia"
LH_SYSLINUX_MENU_LIVE_FAILSAFE_ENTRY="Modo a Prueba de Fallos"
LH_SYSLINUX_MENU_MEMTEST_ENTRY="Prueba de RAM"

MIRROR_DEBIAN="http://localhost:9999/debian"
MIRROR_SECURITY="http://localhost:9999/security/"
MIRROR_BINARY="http://ftp.ch.debian.org/debian/"
MIRROR_BINARY_SECURITY="http://ftp.ch.debian.org/debian-security/"

    #--mirror-debian-installer http://localhost:9999/acervo \
    #--categories "main contrib non-free" \
lb config noauto \
	--apt-recommends disabled \
    --debian-installer live \
    --debian-installer-distribution squeeze \
    --debian-installer-gui false \
    --win32-loader false \
	--distribution squeeze \
    --architecture i386 \
    --archive-areas "main contrib non-free" \
    --mirror-bootstrap ${MIRROR_DEBIAN} \
	--mirror-chroot ${MIRROR_DEBIAN} \
	--mirror-chroot-security ${MIRROR_SECURITY} \
	--mirror-binary ${MIRROR_BINARY} \
	--mirror-binary-security ${MIRROR_BINARY_SECURITY} \
    --hooks "rm_from_init_d.sh mpd_per.sh" \
    --language es \
    --bootappend-live $BOOTAPPEND \
    --hostname flujos.local \
	--iso-application "Flujos Vivos" \
    --iso-volume "flujos-vivos" \
    --iso-publisher "radio.flujos.org" \
    --memtest memtest86+ \
    --net-root-filesystem nfs \
    --net-root-path /srv/debian-live \
    --net-root-server "192.168.1.1" \
    --net-cow-filesystem "nfs" \
    --syslinux-splash "config/binary_syslinux/splash.rle" \
    --syslinux-timeout 4 \
    --syslinux-menu enabled \
    --username radio \
    --apt-secure disabled \
    ${@}
