#!/bin/sh -e

# Static variables
DISTRIBUTIONS="lenny"
FLAVOURS="-flujos"

# Dynamic variables
#ARCHITECTURE="$(dpkg --print-architecture)"
ARCHITECTURE="i386"
DATE=$(date +%Y%m%d)
VERSION=1.0.5
NAME="flujos-vivos-${VERSION}-${DISTRIBUTIONS}-${ARCHITECTURE}"
ISOHYBRID_OPTS="-entry 4 -type 1c"

genBinary ()
{
      TYPE=$*  # iso, usb-hdd, net, tar, squashfs
      buildIMG () 
        {
           
            lh clean --purge
            
            #if [ -e .stage ]
            #    lh clean --purge
            #then
            #fi

            rm -rf cache/packages*
            rm -rf cache/stages_rootfs 
            echo "Build ${FNAME}"
            lh config -b ${TYPE}
            lh build 2>&1 | tee ${FNAME}.log
            echo "copying to ${FNAME}"
            if [ ! -d ${DNAME} ]; then
                mkdir ${DNAME}
            fi
           if [ "${LH_BINARY_IMAGES}" = iso ]; then
              if [ -x "`which isohybrid`" -a "${LH_ARCHITECTURE}" = 'i386' ]; then
             echo "Turning the ISO image into a hybrid one..."
             isohybrid $ISOHYBRID_OPTS "binary[.,-]${EXT}"
              else
             echo "isohybrid was not found, the ISO image won't be a hybrid one"
              fi
           fi

            mv binary[.,-]${EXT} ${DNAME}/${FNAME}
            if [ ${TYPE} = "iso" ]; then
                ND="squashfs"
                if [ ! -d ${ND} ]; then
                    mkdir ${ND}
                fi
                mv binary/*/filesystem.squashfs ${ND}/${NAME}.squashfs

            fi
            for BINARY in $( ls binary[.,-]* )
            do
                if [ ${BINARY#*[.,-]} != "tar.gz" ]; then
                    mv ${BINARY} ${DNAME}/${FNAME}.${BINARY#*[.,-]}
                else
                    mv ${BINARY} ${DNAME}/${FNAME}
                fi
            done
        }
      case "${TYPE}" in 
        iso)
            EXT=${TYPE}
            FNAME="${NAME}.${EXT}"
            DNAME="iso-cdrom"
            buildIMG
        ;;
        usb-hdd)
            EXT=img
            FNAME="${NAME}.${EXT}"
            DNAME="usb-hdd"
            buildIMG
        ;;
        net)
            EXT=net.tar.gz
            FNAME="${NAME}-${EXT}"
            DNAME="net"
            buildIMG
        ;;
    esac
}
        genBinary iso 
        genBinary usb-hdd 
        genBinary net 

